services:
  mediawiki:
    image: mediawiki:1.41
    container_name: talod-wiki
    ports:
      - "8080:80"
    volumes:
      - ./wiki-data/images:/var/www/html/images
      - ./wiki-data/data:/var/www/data
      - ./wiki-data/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./articles:/import:ro
    restart: unless-stopped
